secrets:
    DB_USERNAME: ENC[AES256_GCM,data:lMpprDBliw==,iv:NFuIImMhaAORId7qRCPqq7U6AiGYhgUx91D2m9MJsi8=,tag:KUB2k9GbmNt1KTwmIiDewA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:BVZj2Cc5WEvm5Ima,iv:Enb2Hh/7m9knKk0UzNZHV42LNFvnpUch3lHBuMoH11g=,tag:IK0ELrfITraNEE/EsOxHwA==,type:str]
sops:
    age:
        - recipient: age1qtuhjevdztafh9rpu6fqnpzercgn86c8mfrf4r0vw6cdgh6kvs0qyma2g5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbHVOQ1VPS1MyV0ZTS2dI
            NHNvNEtyRFJ2M21FWnhyYVlRS0RNckhPKzNRCjJCVjVoclNnbzVEdk1URndmOE91
            TkIrUllXb0JncE1OWHVaQjRYYSs3RXcKLS0tIGVyZys4NmlVZ1NYaUE5Rzk3Kzl1
            SlBMeGgwTmFWODZXQnhlZGs2UmtmbE0KqNLadIhaBe8QYshWCvEaXNSRg9pXNSU4
            EvrhwIYa0MqHJQvGTRQ/+6PsEXkLe2/DIEkqYDMKqLk/+Gbl6tHcxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T11:59:21Z"
    mac: ENC[AES256_GCM,data:qCZxeFs+kiPd62WLdAbAamsA/DNZN0oMsatEhcBjQ/BHKhngHPy6dlk8uaVt1lbj7i2IgWpL7suy2U6agubqz7kvH5r3HoxBWnhWV/BCGt5MV+9jB04kwgh3pa+mhPxYG5zCkdUpmkaJZOOe/fjwk8QU3I/F5kcx7A0zhcEhHGE=,iv:HoKvxGFA4H+8wg9QUHDweBMpi8d2aMW3Bpg+TG24st4=,tag:xFRtyMNPFYK1Ipd0lU0c4w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
