secrets:
    DB_USERNAME: ENC[AES256_GCM,data:02Q08ZNGuw==,iv:4J4gW6iisEpm1Q+vX+keK64GH+LIPUpddyP7KwBbZ+g=,tag:C9J4FiSxPaoUFWz3VS80wQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:yXq0k/gzNZYFlmA2,iv:JbZ63QG5F1GOHe8eRLXfrzwuHuP09T+W84xD/sTJrWM=,tag:l+otmSleJKSodv3fG/dnhg==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:MwlebWZvsZ4didX3YNyGrKELDMsF3H18TvXkI3oj59Ejev+GMrfXaPUfsoMCBirfyG3VSga0eC0hjthm4NjSWzR21YqZmbRDAwOAkd2xmtBIj5kNI+BPvFkV4NQUIuUcK5GMPBCfUm88tSbaEA93jmEf4ESUtTddQ/LGurabdqQ=,iv:6/nOUiH5taNhSdqLzlPQV6iF46GpmCibDHh23dqM3pU=,tag:UWbe16usi2ylWHCo812/YQ==,type:str]
sops:
    age:
        - recipient: age1qtuhjevdztafh9rpu6fqnpzercgn86c8mfrf4r0vw6cdgh6kvs0qyma2g5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlakVvYUNSK29lL0RYRkxX
            RVRmQ1c1VzhueDlKeDVRakN1RkppRHpBZHlzCnArRzhIangvT3lTTWwvYi9tWkdX
            YitPdnp5a1JiR2t4UEZTMCtWeWZ3d2sKLS0tIFFOTmw1aGNYUWJvYkRyOFZTS2g0
            dEpOajFFUk9naWRwRnpadUN3azA5bHcKFg1MSCsttSukVdESDakpapB8JEk9IARf
            zSnEROHMMTBjznzHBt1QEqql18nWsSAjJgB1uN5hgndLHnHqy2gvBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T10:48:11Z"
    mac: ENC[AES256_GCM,data:p2wUg6JYCgOi5LEBNekwTuCVw1bEzoMkrm6DgiUO1m2GeEr4Vcg+WWLdAuL74FHpul/3D56Gl4OQCHnM3sxIeTOpe2we8Ran+RcZc1nKCHMha/tg8PR6pqvcBU2/q159DzmCtzu39m4gbZdv4+hOouh+64hFKIPHFtIyXAv7378=,iv:HsqK0dodMTmNRO+AHZj1UW0EbYc81Rq6EupsbwlAGlA=,tag:NEFdvJ5hp4x3NrltSFOBLg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
