image:
  repository: kyumin1227/bannote-user-service
  pullPolicy: IfNotPresent
  tag: "20251124122919-be9504c"
# Environment variables
env:
  GRPC_PORT: "9090"
  DB_HOST: "mysql-user-service.mysql.svc.cluster.local"
  DB_PORT: "3306"
  DB_NAME: "user_service_db"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9092,kafka-controller-1.kafka-controller-headless.kafka.svc.cluster.local:9092,kafka-controller-2.kafka-controller-headless.kafka.svc.cluster.local:9092"
# Secrets
secrets:
  DB_USERNAME: ""
  DB_PASSWORD: ""
