secrets:
    DB_USERNAME: ENC[AES256_GCM,data:0tlOwvB5Zg==,iv:rITFFEUrpNesDoWvpH0VCwFgIYykpv/hPuWZM1IXgKA=,tag:rmULe8eG7iXWOsM21urIiQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:tQBjONjTk0brAKln,iv:6NFpG79SeUrGu9InVIP8zCYLP8IfjJtjIwjqOECiaek=,tag:QH9E9/BO45wjaTFQlvhwbA==,type:str]
sops:
    age:
        - recipient: age1qtuhjevdztafh9rpu6fqnpzercgn86c8mfrf4r0vw6cdgh6kvs0qyma2g5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPY2h2RXJrNjc4NUtrRjYv
            Rm9nQnBFRjl2M25EbThybTYzZVZuOFoydlVJCmRaQmRjZVkzeUdpMmNoZi8xSnV2
            ZUg4L0VrYW44SlpuOTAxRm0xTVRKWjAKLS0tIFl0ajN4SmN0ZFU0QkpvcVIyRmtR
            cDJOSXJBR3BEckRKcGcvNnNWbUhod2MKqxSIK3ax1Tiui1FuC8WqP+RNNRJW4OE4
            7k4HesGTsyOgVIa6WIsQC1Ma70ZtzoVZRQ4txxjZZssuqP+ksJMwtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T11:59:44Z"
    mac: ENC[AES256_GCM,data:W3VdFlraSUdZgDxgM2oa1xQd3M266YLwkR3041/IpXbp+EPAMn6TWg2iah7r+Hf7CBUCn2GoIwic/dgKTvnRX3pNDdlH1dC6aQ7E+bSo5zLiPDi9idK/Kfb5JB88/lQxvnQb6dj9/4ZAP7abcuWZkRz1jzHz2lYjwDUMlAlWw8g=,iv:x3Vw5DX/LKWcAoSoGLTotEk4Hdg+Syc3fJjS+NaJKzg=,tag:AtKSG9ogxR63lhuu52Ivvg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
