secrets:
    DB_USERNAME: ENC[AES256_GCM,data:RYqE5I8VrQ==,iv:9y29VVRTVkNB6J8ApNPnVtQE8tah9nY9aEpMJPr+MZY=,tag:tWBW1FGGqPBLcKyUsOllMA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:MA/HIC8L9BlSTgPM,iv:5uOf5bDfnnAWJhOyEBVbncmvihxE7ll8/4+aAcv81vg=,tag:S6mrB1dKM3YuPof1tQu7gg==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:RRrbkvBQ0mWg/OZlBxWYb8fhwjIgDkgKM0SRCA/2LGaKmoMCSQVYNwL/Wq8aKO9ANf2gSvDm6qbaORkC6tH4WkPc3TYWhJcaQ+UbOBIacgZA82PoKlbSBni4fdrpEDSRQYlKU013MsI+jwQXjtJ+e/ze7ir8a5fd4EcCqPfOwxI=,iv:/xszB9EDQN43rzS7MCn0w77OTeS24SnPP5ReQYDTH/o=,tag:iq/TKOVODh4+qnR6HPMgSQ==,type:str]
sops:
    age:
        - recipient: age1qtuhjevdztafh9rpu6fqnpzercgn86c8mfrf4r0vw6cdgh6kvs0qyma2g5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWW1XU3dqMytkWU5teE1x
            WmorNkUybnVKWDZjMmNUMTJucEhobGxlckUwClJnOVBEdklSUTJLcCtmcGJnUW15
            TTZUZ1BkUS9YaHlPZjg2VUxQREIyUFkKLS0tIGc4OU5MQmpLYllZSmZkTlA3MEc1
            M1A3cEZUQjA0SUVhaG9WNVJsYjJIVmcKXDUyMnmq32XW/H12r90XsQQPXzHcrMD5
            N5BXlV5XB0tGz1YOiTaDhtoIlpgwa3eS8EBOpIr1Yyvw0qVmya4e8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T11:49:15Z"
    mac: ENC[AES256_GCM,data:APaP2n9c5hqV3cwQ6Sxaq/qaNkFJsxJjsFAjxXrgKQeMy8Id7QTPlI4TMgdDc+3Ki+eoBZU02u8tTlXVTZ3S8eRJSK1G9F7CfnK5rXDYuoWS08y/Dc51oxJiuNEtEM8doKrFuu7O3ht0ThbQ8gvZwO/1uL+QBNDEdFE8IgMZ4ms=,iv:p09UOTRpQ6nZ1R8y9oSlLp8ak1GD8gWEmOs/3bUvP2c=,tag:/PnR+i6j2/IbEjv+gcD4ZQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
