apiVersion: v1
kind: Service
metadata:
  name: {{ include "schedule-service.fullname" . }}
  labels:
    {{- include "schedule-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "schedule-service.selectorLabels" . | nindent 4 }}
