image:
  repository: kyumin1227/bannote-api-gateway
  pullPolicy: IfNotPresent
  tag: "20251202143405-daea678"
env:
  SERVER_PORT: "8080"
  USER_SERVICE_ADDR: "user-service.user-service.svc.cluster.local:9090"
  TOKEN_SERVICE_ADDR: "token-service.token-service.svc.cluster.local:9090"
  SCHEDULE_SERVICE_ADDR: "schedule-service.schedule-service.svc.cluster.local:9090"
  STUDYROOM_SERVICE_ADDR: "studyroom-service.studyroom-service.svc.cluster.local:9090"
  GOOGLE_CLIENT_ID: "616869349585-5kkpb0gvqlaq3kl4l67n6tq1nt6fee32.apps.googleusercontent.com"
  FRONTEND_URL: "http://localhost:5173"
  COOKIE_MAX_AGE: "900"
  PUBLIC_KEY_BASE64: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEyV3NZZlAyOG9lMFBwYmw0WUlEVAp1VWxFMEtpUUdTYjVDS0FabVdmUDRKVTB0Zi8zTmxDN2VoLzhmT2FYT3l5eHpHU05LYkREaVBlUWhaNHRRR2UrCmhYM0NINkk4WlBRcVRqWnhubUhiRUlxK1pPTzJvTVBGK25nOUlqRnJwNFdaYnZFOVdsVTZhZlJ2ZlBxVVMvZmgKOEdMM2lJaWpNM3poa0ZEbUVDMTFxQnRLbkRBdFVUVVZiVG1pVjAxZi8rRy9OajlONWdiNXgvc0RidDU4L3FidQpGc2szQkcxSkVQVjFGM2h2KzlrRkhIS3dETmxYalYzV2hMV3piRjVvVlJpWW90UGhZZEplWm9UbXBObm9LZE9yCk42TUZxditEMVBkbisxZkRpc0tzUTM2aUxCNGVCclZWc1F5cHo4VGNaN0VWVm92OXVnUGdtVVR1OXhzNFNocUcKUndJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="
