sops:
  age:
    - recipient: age1qtuhjevdztafh9rpu6fqnpzercgn86c8mfrf4r0vw6cdgh6kvs0qyma2g5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZmdib3gwY0FiRG1DTkJ2
        ZEsyZSt0Mzl5Mnl2aEJETUV4M2lQK29kbHdVCmRtNjZUUEhBdmN6Uk1Cc0hjb2tD
        N095ZHkxY0RsRExGb092dUh6NWt4aU0KLS0tIFl4My9MSWRENWlJYWJTa1A5WTJF
        RGk3Tm5ZYU1hbzlQbHpYZ1VXT09TTDgKhK/dU3tYlbjnCehCmt2a1tGvBdwlAey7
        rn/Ww+rI7kqU6V3q6iZ2nBZ9Ux3SalJH+b8rV0FEbFJu98+pO9dTUw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-19T10:57:01Z"
  mac: ENC[AES256_GCM,data:ge3D37lJEyZh1IbxoxmXOY9ji03R2ASj0RFyfFDUyAZJdOqrTx4TaxIGwJfx8YiuzgyY8FJNJme4nrdGPRvHevA80PudjxCGmnO9zzN/u+5bJQXdiMUk6HLnpEnrphfiVbGLbkeYsHiOH1FKv8x8EzNFN0VPCRXIeO3rhI8kCKs=,iv:y0CLBtOlmeq64sI7bgckioJ4qirj/9UPktUQ9KVg5x4=,tag:EagDmlDOkelP1LvWtYTFkA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
