secrets:
    DB_USERNAME: ENC[AES256_GCM,data:tK8oytce6A==,iv:AnWSIREpAz6ysFwY3ndKtmkVkPe4+MXtMJNyrocpfNw=,tag:EY3dMwvRao4AUs01h4zBNg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:vYmOfhYhFEG9f4tO,iv:myof9ZAPk6zxsHuuMUZwV8rz9fu63dAO3UEdDAPI1OU=,tag:ctglnVCZU2AGPQdkA/vN+Q==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:NA7vQ3ob1nyuqeMhysIPARpIzvrCEQfp0WiZ2T2p0bgwUuHA3dbvwHQTXq2DuzUNTDV0gKEun971n7FUvrTOFIctoL3ktaAqloANoMWOR3faHefn/mkZza5H2gdV0xv/nFzLZzcBxM5WRUv/5ea0aRZuLR0a9tYtSr5nnyz7sNM=,iv:7s2c+2YEx+jX2N7UgTcmabVnfrj7gFfXpHs1yfAgy6c=,tag:h6Cfk59Rv71+ZiU6nMmQtw==,type:str]
sops:
    age:
        - recipient: age1qtuhjevdztafh9rpu6fqnpzercgn86c8mfrf4r0vw6cdgh6kvs0qyma2g5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVTZiSlQ5aUJkRVp3Sk5D
            cW5pY043blZQMms4K2JPcEx4YVEwZzF1Smd3CkxkcDA1NUtzejdBcFRNYTNVbDVJ
            bUNvWGd6ZmpGYjJSbUJzWm4wbytra3MKLS0tIENZdm5ZUlowd3JGRVR4WUVGY1VM
            cEVvM2RTTS9CRlJCUEV2WDROZUJrRW8K+6AvCpdrepe4TTt21bcFARphAsoKo/Ek
            x54J0g/O73jPAgSZ1p+iF0OK9q3BZG8WxYbzEh2mRerIZP0uinmC6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T11:52:16Z"
    mac: ENC[AES256_GCM,data:7vKtNhKiakpNGUD9K3af2xMFMhC9xPHYItcDFqB2KMtGJoR5kq2iPGr2AhZOZRzPGRGHQfiekTNmqMcB+ku/A0nizVoOS5ZxuE7NJYSjAygMk0M0odiO+VkJug39gVcgc/x9MHi73os1Q+KnEMtjyIRqGrlpRN4a5RH6G+Rl6l4=,iv:INQghbp/5k1YaRHGkgIbcV4H+tDtqu8IQjHwAvjiY+E=,tag:fdQEdggjrNKPYnku1uHabA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
