secrets:
    DB_USERNAME: ENC[AES256_GCM,data:Bcu9z+aBtQ==,iv:ysYXgdn1Jj5SafqccQ/1kjBqwmTihZPRI/2XA9Mlq6U=,tag:66mWx0akTQ230vf870K5og==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:3WATFkqx+6QGjnrw,iv:3VSoqxcIngLXa8MRjgQ/sn+2H34YhSpUkV4/Hwk9YP4=,tag:Ah9JxNLziiYDn7oZ/dDXeQ==,type:str]
sops:
    age:
        - recipient: age1qtuhjevdztafh9rpu6fqnpzercgn86c8mfrf4r0vw6cdgh6kvs0qyma2g5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTWtiVWdGd1c5WDc3SC9V
            WlpMbDdJWUdSM2ZJUmJqWUlXajJaZlpQdUFVCnozUHluUkp5b1VLSnB3UWV3MGVP
            cWRVeUNMMThBTUd2SDVGOTNkcDNNZWMKLS0tIHkzaCticXBBK0FFL3BRaDBvald1
            VmFwLy9SdEVFQ0ttR3ZUUkVaTFhhU1kKLud6+mdcb7SNy/lnfUVqZ9g8/jlCbh7F
            RwO4Ui5Td3Ll4nOKYjVTLnD5d6MvhJLScLl2l/tC7Uun3m9v91yeVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T12:19:58Z"
    mac: ENC[AES256_GCM,data:+vf3gBr0a6Gx+ieMfhVUqgqQGE+wNGIrDfZt9M3GnetfZ6klOGIrNXyruxGTTAeMJ+snWsCvBRQ68LhYfugPUcYdBi21QeIw1DuUCKodC8E70tbpzGAma8YT+EA2EfoWSn5g3ff0/7jSonkaNKJ3qAmjbihsASK6b45tGOOigmc=,iv:yqq4PWMVRPYPsMXo9MQ/rW55mfq46qMQTxUvfca5JAQ=,tag:3fKo/exslFlsV2Ma9U8fbg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
