secrets:
    DB_USERNAME: ENC[AES256_GCM,data:ayYO8/Qg9Q==,iv:ujVTIKld1qkOLWp8LxP7DddU+IZFC+MEB0v1wqiFQNs=,tag:afysKpcmJoGreyRXlio0Gw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:z1gcIRZr1XzjRVF7,iv:6WD4R/H2A6pAQZLshkYW3fWoxAEW9EN6Ig3eRhhbq8I=,tag:FdLExzGBJzSGgljFC3bLTQ==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:QtEdveN7t0m+zMhcj/GNL3T1gLvhDXLJ7OrlaWwLRcZnxcFMBEBUFYDDrwaAQC/ZwvHN0giIgXLGkMHLTCKgElFhQxxgUfcqD9exGgXnXCXgu0K3z26asmdk+2Uxzi5NnpP+rnL0Y+Wnp/JHz+Uq2lfpgVrLqXeDVQnUaaWUsUg=,iv:27SdWS+8JstOu6rFN4jtCNXPIo0NIM4WSQ1L64wY3w0=,tag:SehARPvqsCw8qjSXyJsXjw==,type:str]
sops:
    age:
        - recipient: age1qtuhjevdztafh9rpu6fqnpzercgn86c8mfrf4r0vw6cdgh6kvs0qyma2g5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSTBvRVdiR3pCWUl4VnJF
            eDJwS2V2eWZMa3dKaDd6TlVvMW1EeDk3WG1NCkZpaVdVUGMydU5CZjNoYUVKMGR1
            UDJQS3pLMDNWcXdXaXV5TUorZnA0bnMKLS0tIGViWDh4WUR0ZnpwVUsxemtlbGE4
            Z3NycXQvMGF2M1k5NC9jRnBycHcyWlkKGvrf/4EdwD63Xo91QqaRKYVshbNW+NqI
            hEG4qFbjSQnJx2PvGyQvUTprw9pDVIbHLl5SOMO8rfE4B9ZCrTs6jA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T11:52:26Z"
    mac: ENC[AES256_GCM,data:iyBCAo3UQti3YIFbvT8mMadGeLbXj7J9AfMuaHsAsdAFUVGbgJFJwgEIRTtPYyFVD7DfAtm/OGvr/SV9UGaeCFo9+Zj3mhXWCtpe8YoRtoLCugUlY7Iks7E6kOI236eookidj4Hc3/yp1dLFA/J589QcZoGJg9MrFwJbnIwdYiA=,iv:tT+rq5tdQ9pIwrUdMCNP+D8M6BKGYjjGpclL7hDskAI=,tag:vCSkd5g7UvwkwM4rlOIhxg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
