secrets:
    DB_USERNAME: ENC[AES256_GCM,data:Gmyoaok4hg==,iv:xHWof670SuHvmpg27vjfGOayYPI7G3CaU2SJUrt9m1s=,tag:u6QpMQaBhlo9ne6PF1WYbg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:niASPaRqfY0PvKJ+,iv:RlAH/xS/7/BnXW70QlMFkrHagLIhRmFx+rWCpm1tQB0=,tag:Sq4KoHdBPBPSKs6zVFnknA==,type:str]
sops:
    age:
        - recipient: age1qtuhjevdztafh9rpu6fqnpzercgn86c8mfrf4r0vw6cdgh6kvs0qyma2g5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObnQrNExKY2RkWmdscDUy
            WkdyQ0V0d2tOSU9RNThzMG1CVGhFVTk1eldzClowMEp6QXpiRU91SS9Cd0pJZkZV
            enhWVU0xTzM5cG9PM2VRZ29qUzRHZlUKLS0tIHhla3VSMmhBenpkdERML01KNnlU
            di8wakE3NTRQNjUweWZTa2p6dXNZZWcKjilirq3mzVdlmPb+aTC74OOQRuSzNcjR
            fp7Wu6KowzFV1Ns8gAS2yAzR0+NjHJie/onwXIHrkmVHQ+JcqulY8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T12:19:50Z"
    mac: ENC[AES256_GCM,data:lmv2DUBZyNGgIjdXGsP++OlAENaJKR+je7j3/ka6yDmfRZoGEpDsR81/a7C8zszruikw3sxXVaxNujQjqQjPysr75AFfmJ8x9EXapCCna6+S4asGfwSqjvOiWuheXO9ly4g0FcxXR+yHqGQnyXwcaHe4brp/wiJZs8EQ9MagO5g=,iv:Mz58tG8JcmTTpQf9I+tYmg805K3Tty7daC89OgZ66ZY=,tag:SRhB0gjmfb+qfP6liVBuog==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
