image:
  repository: kyumin1227/bannote-studyroom-service
  pullPolicy: IfNotPresent
  tag: "dev-93fdb6d"
# Environment variables
env:
  GRPC_PORT: "9090"
  DB_HOST: "mysql-studyroom-service.mysql.svc.cluster.local"
  DB_PORT: "3306"
  DB_NAME: "studyroom_service_db"
# Secrets
secrets:
  DB_USERNAME: ""
  DB_PASSWORD: ""
