secrets:
    DB_USERNAME: ENC[AES256_GCM,data:Gynq+SvOPw==,iv:3seiLz+uPuQHhhrMgjO6VcOtU++Fesj+fw6RZA6bp8s=,tag:LOt4opIx81zwZaLvGX01Pw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:2wvonx5KHoBhoMyV,iv:W39seLg/uvbUH8Fsv1bvRDyZQ5ViR9sQgAJpuZs1Ir4=,tag:QjSelmk3J4xm6eoRTtSVZg==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:Xh/CDY842SvNoGTM4sT1rRPtnd+sV+aO7wvD6YGlAChQzQEp0PW6Hb9EoqQr3lZ0lUjSdysEgM2m1xJUcnovBxYHpThpTGAWMrhJzC3XE7FmqEe/CABYn2VAV2bMFIyjOBik7kbU2R0wCS6UC9IS83InNhZSbq2uJXDiWAzog0A=,iv:t+CmzKRti0/edV5q0hj3Xj7YhNQGiepqoi4bwYoWtZo=,tag:qujg+CWEhble42+dm2kUKg==,type:str]
sops:
    age:
        - recipient: age1qtuhjevdztafh9rpu6fqnpzercgn86c8mfrf4r0vw6cdgh6kvs0qyma2g5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkK29kLzRzeVB4ZXVJcFhC
            aUcwSlc2ckhERXBWKzFKOHVqT1RqYXlacVIwCmZSdUFFNVhHZlhYMXd1S3drcEoz
            N3RLT0h1M2t4UnhHVFZJT2srVVg0aDgKLS0tIDZOTTZFdUxNdlFBNVIzemhQMEY3
            WDF6S3NvK3FzaU5TZGp1NTdHaVBOSzgKnP/ShUxxn28kealcIxnk1ZOOluDc9AxP
            01iDQF0UN+/16M0Xvtd8oUC0yI90cWMFApMGg1VdzWH0yyKES+jwBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T11:52:07Z"
    mac: ENC[AES256_GCM,data:tVVlJpaAXlPbSIYFUhmjGa2+fzDBAMHPo+OAfSDAUMp7M4sSqN11qnDZOl2eB7uGCBxuEAlLx25jCFuijKzBUlYppo8Eodvh1z2WxHezDkIwv//8hnZisAFAAXMBKazns1Iog3qr6YJ/KtLe6MBApJpW+5khLDKMysFnCMmeUao=,iv:bJYqCPZ2Vbk9QK9oDalrXm/+DqWgefb90AuQ4W9m8og=,tag:UiMTCzvNbXaPr5VUP2A3KQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
