secrets:
    DB_USERNAME: ENC[AES256_GCM,data:in75dxPVnA==,iv:V8vDS2K7x3oPbcqfsMxjL85E72uP8QNU++SXEz3lLlU=,tag:H4pqNe3yg8AVGAxwaw9u8Q==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:5jSTqZb0+R925jgV,iv:HqXjeu4BW9LpI7/c/r03vbt4KRzj+qEMK2amk1R7igc=,tag:7BA4KclP6kyi//IscDCBrg==,type:str]
sops:
    age:
        - recipient: age1qtuhjevdztafh9rpu6fqnpzercgn86c8mfrf4r0vw6cdgh6kvs0qyma2g5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTK1A1Qk5QRnhFSkRXVTIx
            Vk5QS0QzVVVDOXRjN1oxV1B1dG1ob21wWlhzCmhJSWJ6V251WDVTYXd4VUNkR0hR
            aXdXWEExSTFMSld6ckVudmdHdHM1MDQKLS0tIGRSWHFFNUxQQm9CMkpkekpHQXl4
            WEhkekdWT25JSlpEZkZuOEd4VXR0NHcKTKbjWtFGP1GujL5/LGSwLeR/OiuHnPzE
            d0FlMoPTFG7qFFniafBRpb1WZSjFsv4qBaX0Qgr7UPqWEzMor3SR3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T12:20:08Z"
    mac: ENC[AES256_GCM,data:Sb5Y3F1/WxtH8D9Nk4MTZ+wd2PfMNB201JfCGeEs+mvBMpE+XwQdF79bvkLrWeOsxErWmHnLuOQ0h/0Oh6eS3DcZQ2CaWcrWqBSm/4BtEFHFkrmu/Yu9ydtWU181CxMWN96iqj2dtiQXtPg58dtDmqSlzRzSwv0IpPiI+rBcRTc=,iv:Yh6wLlwo3q4LKNSBb+y07GBvu1BuhAILn0LgbZ6xszM=,tag:Lfn0si50G4RgNICm7JIa0A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
