sops:
  age:
    - recipient: age1qtuhjevdztafh9rpu6fqnpzercgn86c8mfrf4r0vw6cdgh6kvs0qyma2g5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZWNQRllCUzBMY25Qc3RB
        dHB0ZjlPNXFqeFNVdmRpa2VFdzFzeFp4RDBzCm5HUCtxNHRxSDFZSnRMMS9wRHp1
        bEZTbVRsNFJFeDRZdmNjMSt1T3UwZzQKLS0tIGlkUC81aWN3K1huSkdJbjlxQUZ0
        UzhtQ1NSMHplUlovTERXY0dZeEZyeXcKqOF+yPSoGwtygDPrlio2ui/5fTDRE96Z
        xSOvMn5zhTXdIlflkwjE73YORlJssTlQZQdb0u/erwwLmqiOoPAFwg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-19T10:56:52Z"
  mac: ENC[AES256_GCM,data:jMQryXFfyXj07zmFf8U4j7Jskgndy9QFf9GfTicjFD2O11MeZ1h7bje+WvYomJ87XaI66EzNNHrtUydyA3/r7EJhcFsioCIYguSjsB9dV5Kz1widPm7neJSe7xY0jHhGPLgAJN00gibTEmTcsa7f76reT28rVKMChiK6Ie36Nh0=,iv:biyGLvv+VJ1GXTMUqekpeldr+GtE7YueByM50ZXWSeY=,tag:vdLQGoC/hnQNE8G5euGPGg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
