secrets:
    DB_USERNAME: ENC[AES256_GCM,data:iwz81GzGmg==,iv:XCpI7vpdc81dAbgS3ts2U5rP0j2EJxR5l7qdPDzsvRU=,tag:8Zz6iMNnMs1Jb7j4MQfNTw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:xkLsp4ioC6z+w+RU,iv:yn8cbPiGQ9l/Lb5+sHzN9U8yGuYjWoNFeVY0hCPCxkM=,tag:FY/zFcBLDynIAY4Fx+twtw==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:3Kt92hEuEUx/Xd/J6xl8p9R+0ICF5lVQwhyphku/K7uNUZEGnk29IX5xGr6lR9ynVfx6tUDMAQgercT/lgRJT8s5uGVIUymTv9ldgeeRaJIRKWlZ3vzYCu7/LBYfv7OpbsB4aLttvRacg+sdALLjpFsKm6d1phhfVNT4eiLjtKM=,iv:ZARAfUlCBAGwlHUWN6MsLCQaXv+bZfMzOVbDlyBq6E0=,tag:/f3LP2dcNCNXmMvj0mVx2A==,type:str]
sops:
    age:
        - recipient: age1qtuhjevdztafh9rpu6fqnpzercgn86c8mfrf4r0vw6cdgh6kvs0qyma2g5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwcE9UZkRPYmM0L1IwMU1k
            WkxEK0M5SDJVMGJYOW5PZkUyWXdYa0MrL3drCkJIc3ZuRUE4cUhzMTU3N2pEcDdY
            NlNKNlc5WGV2NC85VHJsd29ZQXQ4MWsKLS0tICtKeXJOaHAwVDZINGRwbHNBY3Bo
            VW5qaTQyM2hYeDdUSGNqaTZGWGhOaEUKEP+/azNqrRaOBWFtVbS7LUr92uqA9kNx
            sxXyCrA/KGziUExla8/B7Gm5RMfqmoII9jd7p1H5yCU08iHQBrH4eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T11:48:59Z"
    mac: ENC[AES256_GCM,data:XROzIMyzUOcYarko/CSJrN6ZkFPPad3ZcVKPv3NzVkDjftqkbH9ibd7mftQZLtvXn96gmWCqPWCyikTtn1quPX9DglBvG1XfM9wSowkHgus8CbUyQDYWkDkclojt7ZTaCYsSyQO5p8G1voL7/Jzlgkr997AfJE0fKULCwdj6pp4=,iv:nDDSPt4r3L8TPrZbCZUSC6774sjnig4xwoGz14Khfv4=,tag:gxf77Wf+EITNasR/BQVPPg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
