secrets:
    DB_USERNAME: ENC[AES256_GCM,data:0r/gneyOsQ==,iv:qwMLfsz54tvNQ1wNXI9NkGAeHVFwRQcv7bJthpQ7120=,tag:9q6xY6+TfYZMIkq++W2eow==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:JOWx4j+upHaQ1c1R,iv:rT5IkLPU6zyHv94TQXnGC0zUxFHgO6EvTA14xAUUGu0=,tag:JOF06pOlS/8H8yJ8NM3npg==,type:str]
sops:
    age:
        - recipient: age1qtuhjevdztafh9rpu6fqnpzercgn86c8mfrf4r0vw6cdgh6kvs0qyma2g5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRnE3TGNWQjExYXZOWm5y
            TEZLK2xhbExyN28wcVlneTFUS1B5ajIwTFhFCmI4UnFYdXVCT0ZadVVNNG90ckx3
            djZCQ1lYNmJVSk40TjdvdXRiMTZNODQKLS0tICtjbVUrR1pJZUFtQjdtTTNZbHpT
            clFwZTd4Mk1CTFdOK2VmSXFsSFhHRm8KGDZEXOE1PHSJh7/tl24zsAzeT1CO7p1n
            zd8rmsXLGqKiVgMiVlepAPMRpj7SGEs2w046Q+l3F5d6AoM96caCNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T11:59:35Z"
    mac: ENC[AES256_GCM,data:lvvVePvQbfzsgE2gQ0F/wKs3XX35zG7e2aDg4tgUSnqDMfCGOzxyjgbBZJSpGkX545IcRIdUJI/GAV9xpn+wVcuVCrcuWT2K7Al2b9Yswf2/3IWXXt3FQbUor0BeuJhMqfZ2/1jMjP476Kxo+Y1cJRkdv076u+sXxystDvRFUyA=,iv:7Su+HbSoTQfAznmWf6fuzZR9hBaq0qJ52RbAWo/VZfA=,tag:o3IHQWl/5JnGElbm1cC3nA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
